const components = {
  Clock: () => import('components/other/Clock.vue'),
  Video: () => import('components/media/Video.vue'),
  DragList: () => import('pages/drag.vue'),
  FormEl: () => import('components/other/FormEl.vue'),
  Container: () => import('components/pixi/Container.vue'),
  DrawMoveShape: () => import('components/pixi/DrawMoveShape.vue'),
  PlaceHolder: () => import('components/other/placeholder.vue'),
  NewSprite: () => import('components/canvas/new-sprite.vue'),
  PixiDemo: () => import('components/pixi/pixi-demo.vue'),
  Battary: () => import('components/animate/Battary.vue'),
  Easing: () => import('components/animate/Easing.vue'),
  ColorBoard: () => import('components/cg/color-board.vue'),
  Ball: () => import('components/cg/ball.vue'),
  PixiInit: () => import('components/pixi/hello-world.vue'),
  PixiSprite: () => import('components/pixi/sprite-from-tileset.vue'),
  PixiData: () => import('components/pixi/sprite-from-data.vue'),
  LeafVolumn: () => import('components/pixi/leaf-volumn.vue'),
  Sphere: () => import('components/sphere.vue'),
  Light: () => import('components/cg/light.vue'),
  Cube: () => import('components/3d/cube.vue'),
  FunctionMath: () => import('components/cg/function-math.vue'),
  Intersection: () => import('components/canvas/intersection.vue'),
  ThreePrimaryColor: () => import('components/canvas/three-primary-colors.vue'),
  FreeRect: () => import('components/canvas/free-rect.vue'),
  Move: () => import('components/other/move.vue'),
  Poly: () => import('components/canvas/poly.vue'),
  Carousels: () => import('components/animate/carousels.vue'),
  CarouselsCard: () => import('components/animate/carousel-card.vue'),
  CodeMirror: () => import('components/other/code-mirror.vue'),
};

export default components;
